import {resultPanels} from './helpers.jsx';

export const FETCH_DB_DATA = 'FETCH_DB_DATA';
export const RECEIVE_DB_DATA = 'RECEIVE_DB_DATA';

export const FETCH_PLAYER_DATA = 'FETCH_PLAYER_DATA';
export const RECEIVE_PLAYER_DATA = 'RECEIVE_PLAYER_DATA';

export const FETCH_TOURNAMENT_DATA = 'FETCH_TOURNAMENT_DATA';
export const RECEIVE_TOURNAMENT_DATA = 'RECEIVE_TOURNAMENT_DATA';

export const FETCH_GAME_DATA = 'FETCH_GAME_DATA';
export const RECEIVE_GAME_DATA = 'RECEIVE_GAME_DATA';

export const FETCH_GAME_EVAL_DATA = 'FETCH_GAME_EVAL_DATA';
export const RECEIVE_GAME_EVAL_DATA = 'RECEIVE_GAME_EVAL_DATA';

export const FETCH_MOVE_EVAL_DATA = 'FETCH_MOVE_EVAL_DATA';
export const RECEIVE_MOVE_EVAL_DATA = 'RECEIVE_MOVE_EVAL_DATA';

export const FETCH_MOVE_SUMMARY_DATA = 'FETCH_MOVE_SUMMARY_DATA';
export const SELECT_DB = 'SELECT_DB';
export const SELECTION_CHANGED = 'SELECTION_CHANGED';
export const SELECT_SHOWTYPE = 'SELECT_SHOWTYPE';
export const SELECT_GAME = 'SELECT_GAME';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export const LOGIN_OR_REGISTER = 'LOGIN_OR_REGISTER';
export const LOGIN_OR_REGISTER_FAILED = 'LOGIN_OR_REGISTER_FAILED';
export const LOGIN_OR_REGISTER_SUCCEEDED = 'LOGIN_OR_REGISTER_SUCCEEDED';

export const SELECT_LOGIN_WINDOW = 'SELECT_LOGIN_WINDOW';

export const FETCH_USER = 'FETCH_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const STATUS_RECEIVED = 'RECEIVED';
export const STATUS_ERROR = 'ERROR';

